# Generated by Django 2.2.6 on 2019-11-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0021_auto_20191109_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], max_length=120),
        ),
    ]
