# Generated by Django 2.2.6 on 2019-10-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20191020_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
    ]
